[package]
name = "morse"
version = "0.1.0"
authors = ["Tjeerd Lafebre <tjeerd.lafebre@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
